"use client";

interface PrintFooterProps {
  text?: string;
}

export default function PrintFooter({
  text = "This document is generated by the Performance Management System, University of Lahore.",
}: PrintFooterProps) {
  return (
    <div className="print-only" style={{ display: "none" }}>
      <div className="print-doc-footer">{text}</div>
    </div>
  );
}
